echo git branch show

diff --git a/.github/workflows/hello-world.yml b/.github/workflows/hello-world.yml
--- a/.github/workflows/hello-world.yml
+++ b/.github/workflows/hello-world.yml
@@ -6,38 +6,38 @@ on:
 
 
 jobs:
-  fetch-environments:
-    runs-on: ubuntu-latest
-    outputs: 
-      enviros: ${{ steps.get-envs.outputs.envs }}
-    steps:
-      - id: get-envs
-        run: |            
-          environments=()
-          pageNum=1
-          total=1
+  # fetch-environments:
+  #   runs-on: ubuntu-latest
+  #   outputs: 
+  #     enviros: ${{ steps.get-envs.outputs.envs }}
+  #   steps:
+  #     - id: get-envs
+  #       run: |            
+  #         environments=()
+  #         pageNum=1
+  #         total=1
           
-          while [ ${#environments[@]} -lt $total ]; do
-              res=$(curl -s -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{github.token}}" "https://api.github.com/repos/${{github.repository}}/environments?per_page=100&page=$pageNum")
+  #         while [ ${#environments[@]} -lt $total ]; do
+  #             res=$(curl -s -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{github.token}}" "https://api.github.com/repos/${{github.repository}}/environments?per_page=100&page=$pageNum")
               
-              envs=($(echo "$res" | jq -r '.environments[].name'))
-              total=$(echo "$res" | jq -r '.total_count')
+  #             envs=($(echo "$res" | jq -r '.environments[].name'))
+  #             total=$(echo "$res" | jq -r '.total_count')
               
-              if [ ${#envs[@]} -eq 0 ]; then
-                  echo "An error has occurred while attempting to fetch the environments"
-                  exit 1
-              fi
+  #             if [ ${#envs[@]} -eq 0 ]; then
+  #                 echo "An error has occurred while attempting to fetch the environments"
+  #                 exit 1
+  #             fi
               
-              environments+=("${envs[@]}")
-              ((pageNum++))
-          done
+  #             environments+=("${envs[@]}")
+  #             ((pageNum++))
+  #         done
           
-          envlist=$(printf '%s\n' "${environments[@]}" | jq -R . | jq -sc .) >> "$GITHUB_OUTPUT"
+  #         envlist=$(printf '%s\n' "${environments[@]}" | jq -R . | jq -sc .) >> "$GITHUB_OUTPUT"
 
-          echo envs=$envlist
-          # eg ["productions","develop"]
+  #         echo envs=$envlist
+  #         # eg ["productions","develop"]
 
-          echo envs=$envlist >> $GITHUB_OUTPUT
+  #         echo envs=$envlist >> $GITHUB_OUTPUT
 
   fetch-release-details:
     runs-on: ubuntu-latest
@@ -56,16 +56,6 @@ jobs:
           echo "Using Release Tag: ${{github.event.release.tag_name}}"
           echo "Using Release ID: ${{github.event.release.id}}"
   
-  fetch-branch-name:
-    runs-on: ubuntu-latest
-    outputs: 
-      enviros: ${{ steps.get-name.outputs.branch_name }}
-    steps:
-      - run: echo ${{ github.ref}}
-      - run: git branch --show-current
-      - id: get-name
-        run: echo "tag=$( git branch --show-current )" >> "$GITHUB_OUTPUT" 
-
   fetch-branch-name2:
     runs-on: ubuntu-latest
     outputs: 
@@ -73,7 +63,6 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
-      - run: echo ${{ github.ref}}
-      - run: git branch --show-current
+      - run: echo $(git branch --show-current)
       - id: get-name
         run: echo "tag=$( git branch --show-current )" >> "$GITHUB_OUTPUT" 
