flow to calc env and slot

diff --git a/.github/workflows/hello-world.yml b/.github/workflows/hello-world.yml
--- a/.github/workflows/hello-world.yml
+++ b/.github/workflows/hello-world.yml
@@ -41,31 +41,70 @@ jobs:
 
           echo envs=$envlist >> $GITHUB_OUTPUT
 
-  fetch-release-details:
-    runs-on: ubuntu-latest
-    outputs:
-      TAG_NAME: ${{steps.get-tag.outputs.tag}}
-    steps:
+  # fetch-release-details:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     TAG_NAME: ${{github.event.release.tag_name}}
+  #     IS_PRE: ${{ github.event.release.prerelease }}
+  #   steps:
       
-      # - name: Checkout Repository
-      #   uses: actions/checkout@v3
+  #     # - name: Checkout Repository
+  #     #   uses: actions/checkout@v3
 
-      - id: get-tag
-        run: echo "tag=${{github.event.release.tag_name}}" >> "$GITHUB_OUTPUT"          
+  #     - id: get-tag
+  #       run: echo "tag=${{github.event.release.tag_name}}" >> "$GITHUB_OUTPUT"          
 
-      - name: Use Release Details
-        run: |
-          echo "Using Release Tag: ${{github.event.release.tag_name}}"
-          echo "Using Release ID: ${{github.event.release.id}}"
+  #     - name: Use Release Details
+  #       run: |
+  #         echo "Using Release Tag: ${{github.event.release.tag_name}}"
+  #         echo "Using Release ID: ${{github.event.release.id}}"
   
-  fetch-branch-name2:
+  # fetch-branch-name:
+  #   runs-on: ubuntu-latest
+  #   outputs: 
+  #     enviros: ${{ github.event.release.target_commitish }}
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #     - run: echo ${{ github.event.release.target_commitish }}
+  #     - run: echo helloworld
+  #     - id: get-name
+  #       run: echo "tag=${{ github.event.release.target_commitish }}" >> "$GITHUB_OUTPUT" 
+
+  think:
     runs-on: ubuntu-latest
+    needs: fetch-environments
     outputs: 
-      enviros: ${{ steps.get-name.outputs.branch_name }}
+      version: ${{github.event.release.tag_name}}
+      environment: ${{steps.calculate-slot.outputs.environment}}
+      slot: ${{steps.calculate-slot.outputs.slot}}
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-      - run: echo ${{ github.event.release.target_commitish }}
-      - run: echo helloworld
-      - id: get-name
-        run: echo "tag=${{ github.event.release.target_commitish }}" >> "$GITHUB_OUTPUT" 
+      - id: calculate-slot
+        run: |
+          if [[ "${{github.event.release.target_commitish}}" == "main" ]]; then
+              environment="production"
+              if [[ "${{github.event.release.prerelease}}" == "true" ]]; then
+                  slot="pre-prod"
+              else
+                  slot=""
+              fi
+          else
+              if [[ "${{github.event.release.prerelease}}" == "false" ]]; then
+                  echo "Error: Non pre-release on a non-main branch" >&2
+                  exit 1
+              fi
+
+              slot="${{github.event.release.target_commitish}}"
+              if [[ " ${${{needs.fetch-environments.outputs.enviros}}[@]} " =~ " ${${{github.event.release.target_commitish}}} " ]]; then
+                  environment="${{github.event.release.target_commitish}}"
+              else
+                  environment="develop"
+              fi
+          fi
+
+          echo "Version: ${{github.event.release.tag_name}}"
+          echo "Environment: $environment"
+          echo "Slot: $slot"
+
+          echo "environment=$environment" >> $GITHUB_OUTPUT
+          echo "slot=$slot" >> $GITHUB_OUTPUT
